PetLoveWeb/Controllers/AnimalController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PetLoveWeb.Banco;
using PetLoveWeb.Gerenciadores;
using System.Web.Security;
using PetLoveWeb.Models;

namespace PetLoveWeb.Controllers
{ 
    public class AnimalController : Controller
    {
        //
        // GET: /Turma/

        public ViewResult Index()
        {
            string userId = Membership.GetUser().ProviderUserKey.ToString();
            return View(GerenciadorAnimal.GetInstance().ObterPorUsuario(Convert.ToInt32(userId)));
        }

        //
        // GET: /Turma/Details/5

        public ViewResult Details(int id)
        {
            AnimalModel animal = GerenciadorAnimal.GetInstance().Obter(id);

            return View(animal);
        }

        //
        // GET: /Turma/Create

        public ActionResult Create()
        {
            ViewBag.Racas = new SelectList
                    (
                        new List<SelectListItem>(),
                        "Id_Raca",
                        "NomeRaca"
                    );
            return View();
        }

        //
        // POST: /Turma/Create

        [HttpPost]
        public ActionResult Create(AnimalModel model)
        {
            if (ModelState.IsValid)
            {
                string userId = Membership.GetUser().ProviderUserKey.ToString();
                model.Id_Usuario = Convert.ToInt32(userId);
                //Redirecionar para a tela de localização
                //return RedirectToAction("Index");
            }
            else
            {
                if (model.Tipo == "C")
                {
                    ViewBag.Racas = new SelectList
                    (
                        GerenciadorRaca.GetInstance().ObterCaes(),
                        "Id_Raca",
                        "NomeRaca"
                    );
                }
                else if (model.Tipo == "G")
                {
                    ViewBag.Racas = new SelectList
                    (
                        GerenciadorRaca.GetInstance().ObterGatos(),
                        "Id_Raca",
                        "NomeRaca"
                    );
                }
                else
                {
                    ViewBag.Racas = new SelectList
                        (
                            new List<SelectListItem>(),
                            "Id_Raca",
                            "NomeRaca"
                        );
                }
            }
            
            return View(model);
        }

        //
        // GET: /Turma/Edit/5

        public ActionResult Edit(int id)
        {
            AnimalModel animal = GerenciadorAnimal.GetInstance().Obter(id);
            return View(animal);
        }

        //
        // POST: /Turma/Edit/5

        [HttpPost]
        public ActionResult Edit(AnimalModel model)
        {
            if (ModelState.IsValid)
            {
                //GerenciadorTurma.GetInstance().Editar(model);
                return RedirectToAction("Index");
            }
            return View(model);
        }

        //
        // GET: /Turma/Delete/5

        public ActionResult Delete(int id)
        {
            AnimalModel animal = GerenciadorAnimal.GetInstance().Obter(id);
            ViewBag.Error = "";
            return View(animal);
        }

        //
        // POST: /Turma/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            AnimalModel animal = GerenciadorAnimal.GetInstance().Obter(id);
            try
            {
                ViewBag.Error = "Não foi possível remover esta animal, pois devem existir atividades associadas. Se não existirem animals associadas contacte o ADM do sistema.";
                return View(animal);
            }
            catch (Exception)
            {
                ViewBag.Error = "Não foi possível remover esta animal, pois devem existir atividades associadas. Se não existirem animals associadas contacte o ADM do sistema.";
                throw;
            }
            return RedirectToAction("Index");
        }

    }
}

PetLoveWeb/Views/Shared/_Grid.cshtml
@using GridMvc.Columns
@model GridMvc.IGrid
@if (Model == null) { return; }
@if (Model.RenderOptions.RenderRowsOnly)
{
    @RenderGridBody();
}
else
{
    <div class="grid-mvc" data-lang="@Model.Language" data-gridname="@Model.RenderOptions.GridName" data-selectable="@Model.RenderOptions.Selectable.ToString().ToLower()" data-multiplefilters ="@Model.RenderOptions.AllowMultipleFilters.ToString().ToLower()">
        <div class="grid-wrap">
            <table class="table table-striped grid-table">
                @* Draw grid header *@
                <thead>
                    @RenderGridHeader()
                </thead>
                <tbody>
                    @RenderGridBody()
                </tbody>
            </table>
            @RenderGridPager()
        </div>
    </div>
}
@helper RenderGridBody()
{
    if (!Model.ItemsToDisplay.Any())
    {
    <tr class="grid-empty-text">
        <td colspan="@Model.Columns.Count()">
            @Model.EmptyGridText
        </td>
    </tr>
    }
    else
    {
        foreach (object item in Model.ItemsToDisplay)
        {
    <tr class="grid-row @Model.GetRowCssClasses(item)">
        @foreach (IGridColumn column in Model.Columns)
        {
            @column.CellRenderer.Render(column, column.GetCell(item))
        }
    </tr>
        }
    }
}
@helper RenderGridHeader()
{
    <tr>
        @foreach (IGridColumn column in Model.Columns)
        {
            @column.HeaderRenderer.Render(column)
        }
    </tr>
}
@helper RenderGridPager()
{
    if (Model.EnablePaging && Model.Pager != null)
    {
    <div class="grid-footer">
        @Html.Partial(Model.Pager.TemplateName, Model.Pager)
    </div>
    }
}

PetLoveWeb/Views/Shared/_GridPager.cshtml
@model GridMvc.Pagination.GridPager
@if (Model == null || Model.PageCount <= 1)
{
    return;
}
<div class="grid-pager">
    <ul class="pagination">
        @if (Model.CurrentPage > 1)
        {
            <li>
                <a href="@Model.GetLinkForPage(Model.CurrentPage - 1)">«</a>
            </li>
        }

        @if (Model.StartDisplayedPage > 1)
        {
            <li>
                <a href="@Model.GetLinkForPage(1)">1</a>
            </li>
            if (Model.StartDisplayedPage > 2)
            {
            <li><a href="@Model.GetLinkForPage(Model.StartDisplayedPage - 1)">...</a></li>
            }
        }
        @for (int i = Model.StartDisplayedPage; i <= Model.EndDisplayedPage; i++)
        {
            if (i == Model.CurrentPage)
            {
            <li class="active"><span>@i</span></li>
            }
            else
            {
            <li><a href="@Model.GetLinkForPage(i)">@i</a></li>
            }
        }
        @if (Model.EndDisplayedPage < Model.PageCount)
        {
            if (Model.EndDisplayedPage < Model.PageCount - 1)
            {
            <li><a href="@Model.GetLinkForPage(Model.EndDisplayedPage + 1)">...</a></li>
            }
            <li><a href="@Model.GetLinkForPage(Model.PageCount)">@Model.PageCount</a></li>
        }
        @if (Model.CurrentPage < Model.PageCount)
        {
            <li><a href="@Model.GetLinkForPage(Model.CurrentPage + 1)">»</a></li>
        }
    </ul>
</div>

PetLoveWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title</title>
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
    <script src="@Url.Content("~/Scripts/jquery-1.5.1.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/modernizr-1.7.min.js")" type="text/javascript"></script>
</head>
<body>
    <div class="page">
        <header>
            <div id="title">
                <h1>Pet Love</h1>
            </div>
            <div id="logindisplay">
                @Html.Partial("_LogOnPartial")
            </div>
            <nav>
                <ul id="menu">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    @if (Request.IsAuthenticated)
                    {
                    <li>@Html.ActionLink("Meus Animais", "Index", "Animal")</li>
                    <li>@Html.ActionLink("Maps", "Listagem", "Home")</li>
                    }
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                </ul>
            </nav>
        </header>
        <section id="main">
            @RenderBody()
        </section>
        <footer>
        </footer>
    </div>
</body>
</html>

PetLoveWeb/Views/Shared/_LogOnPartial.cshtml
@if(Request.IsAuthenticated) {
    <text>Bem-Vindo(a) <strong>@User.Identity.Name</strong>!
    [ @Html.ActionLink("Meus Dados", "ChangePassword", "Account") ]
    [ @Html.ActionLink("Sair", "LogOff", "Account") ]</text>
}
else {
    @:[ @Html.ActionLink("Cadastrar-se", "Register", "Account") ]
    @:[ @Html.ActionLink("Entrar", "LogOn", "Account") ]
}